version: '3.4'
services:
    loki:
        image: grafana/loki:3.1.0
        depends_on:
            - minio
        ports:
            - 3100:3100

    minio:
        image: minio/minio:RELEASE.2024-02-24T17-11-14Z
        entrypoint: sh
        command: -c 'mkdir -p /data/loki && /usr/bin/minio server --console-address :9001 /data'
        environment:
            - MINIO_ACCESS_KEY=loki
            - MINIO_SECRET_KEY=supersecret
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - .data-minio:/data:delegated
